### ISSUE TITLE
mockers_codegen fails to compile with rust 1.26.0

### ISSUE THREAD

**Issue by asomers** [kriomant/mockers#25]
Using a nightly toolchain from 2-26-2018:
```
  Compiling mockers_codegen v0.9.3
error[E0599]: no associated item named `Public` found for type `syntax::codemap::Spanned<syntax::ast::VisibilityKind>` in the current scope
   --> /home/somers/.cargo/registry/src/github.com-1ecc6299db9ec823/mockers_codegen-0.9.3/src/lib.in.rs:589:14
    |
589 |         vis: Visibility::Public,
    |              ^^^^^^^^^^^^^^^^^^ associated item not found in `syntax::codemap::Spanned<syntax::ast::VisibilityKind>`

error[E0599]: no associated item named `Inherited` found for type `syntax::codemap::Spanned<syntax::ast::VisibilityKind>` in the current scope
   --> /home/somers/.cargo/registry/src/github.com-1ecc6299db9ec823/mockers_codegen-0.9.3/src/lib.in.rs:683:14
    |
683 |         vis: Visibility::Inherited,
    |              ^^^^^^^^^^^^^^^^^^^^^ associated item not found in `syntax::codemap::Spanned<syntax::ast::VisibilityKind>`

error[E0599]: no associated item named `Inherited` found for type `syntax::codemap::Spanned<syntax::ast::VisibilityKind>` in the current scope
   --> /home/somers/.cargo/registry/src/github.com-1ecc6299db9ec823/mockers_codegen-0.9.3/src/lib.in.rs:833:14
    |
833 |         vis: Visibility::Inherited,
    |              ^^^^^^^^^^^^^^^^^^^^^ associated item not found in `syntax::codemap::Spanned<syntax::ast::VisibilityKind>`

error: aborting due to 3 previous errors

error: Could not compile `mockers_codegen`.

To learn more, run the command again with --verbose.
```

**Comment by kriomant** [comment]
Fixed in 0.9.4
