### ISSUE TITLE
Build broken on rustc stable 1.15.0

### ISSUE THREAD

**Issue by matthauck** [kriomant/mockers#12]
I had assumed that mockers would work on stable 1.15.0 now that it is released, but build fails:

>   Compiling mockers_codegen v0.5.7
> error[E0554]: #[feature] may not be used on the stable release channel
>  --> /Users/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/mockers_codegen-0.5.7/src/lib.rs:1:41
>   |
> 1 | #![cfg_attr(not(feature="with-syntex"), feature(quote, rustc_private))]
>   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to previous error
> 
> error: Could not compile `mockers_codegen`.

**Comment by matthauck** [comment]
> $ rustc --version
> rustc 1.15.0 (10893a9a3 2017-01-19)

**Comment by matthauck** [comment]
Sorry, PR title here pretty poorly chosen probably. I realize that you have very explicitly tied the build of mockers to nightly rust, but now that 1.15 has "macros 1.1" support, couldn't this ban be lifted to allow it on stable as well?

**Comment by kriomant** [comment]
Please look at [air_codegen example](../tree/master/examples/air_codegen/Cargo.toml), you need to tune `mockers` and `mockers_codegen` features.

**Comment by bkchr** [comment]
@kriomant what is required for your plugin to work on rust stable? Because as @matthauck I thought that with 1.15 your plugin should work with stable?

**Comment by kriomant** [comment]
`mockers` can work on rust stable, but usage is not as smooth as on nightly, you must use code generation. Please look at [air_codegen example](../tree/master/examples/air_codegen/) and try to build it on stable rust.

**Comment by bkchr** [comment]
Yeah I know that, but I spoken about the smooth nightly way on stable ;)

**Comment by kriomant** [comment]
Unfortunately, new derive system implemented in stable doesn't support #[derive] directives on traits, only on structs, so smooth way is impossible.

**Comment by la10736** [comment]
I didn't do it yet but maybe we can take a look to `serde_derive` to see how they do it https://serde.rs/codegen.html . There are some chances to get some inspiration from it.

**Comment by kriomant** [comment]
`serde_derive` uses derive mechanism added in 1.15 which doesn't support derive clauses on traits, only on structs. It is fine for `serde` (in fact, this mechanism was developed to make `serde` available on stable in the first place), but not for `mockers`.

**Comment by la10736** [comment]
:cry:

**Comment by la10736** [comment]
Ok, I will investigate `macro_attr` at https://docs.rs/macro-attr/0.2.0/macro_attr/ . Maybe will not so smooth but  seams a way to build mock on stable with just a little overhead.
